name: Code Quality and Security Scanner

on:
  workflow_dispatch

jobs:
  scan-and-test:
    name: Lint and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Bash Linting
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
          additional_files: 'start_chat.bash test_chat.sh'
          severity: error

      # 2. Dockerfile Linting
      - name: Run Hadoling
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          # Fails pipeline on warging or errors
          failure-threshold: error
          
      # 3. Build the Image (Required before Trivy can scan it)
      - name: Build Docker Image
        run: |
          docker build -t bashgpt:latest .
          docker images
       
        

      # 4. Image Vulnerability Scanning
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.36.0 
        with:
          image-ref: 'bashgpt:latest'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'



  consolidate:
    name: Consolidate Results
    runs-on: ubuntu-latest
